name: amr-fcgr-prediction
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.8.0
  - fastai=2.8.4
  - scikit-learn=1.6.1
  - pandas=2.2.2
  - numpy=2.0.2
  - sourmash=4.9.4
  - biopython=1.85
  - abricate=1.0.1
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - plotly=5.24.1
